name: "Release"

on:
  push:
    paths:
      - ".github/workflows/hackage.yml"
  release:
    types:
      - created
      - published

concurrency:
  group: hackage
  cancel-in-progress: false

jobs:
  publish-to-hackage:
    name: "Publish to Hackage"
    runs-on: ubuntu-latest
    environment:
      name: ${{ (github.event.action == 'published' && 'Hackage') || '' }}
      url: "https://hackage.haskell.org/package/persistent-index-${{ steps.determine-version.outputs.version }}"

    steps:
      - name: "Dump context"
        shell: bash
        env:
          EVENT_DATA: "${{ toJson(github) }}"
        run: echo $EVENT_DATA | jq

      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Determine version"
        id: determine-version
        shell: bash
        run: |
          PACKAGE_VERSION="$(yq '.version' package.yaml)"
          echo $PACKAGE_VERSION
          echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT

      - name: "Install Stack"
        uses: haskell-actions/setup@v2
        id: install-haskell
        with:
          stack-no-global: true
          enable-stack: true
          stack-version: "latest"

      - name: "Check source distribution"
        shell: bash
        run: stack sdist .

      - name: Publish `home-assistant-client`
        if: startsWith(github.ref, 'refs/tags/v') && github.event.action == 'published'
        shell: bash
        run: stack upload . --candidate --no-save-hackage-creds
        env:
          HACKAGE_KEY: ${{ secrets.HACKAGE_KEY }}
